//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Services.Drv.Emera.Culture {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sys.Services.Drv.Emera.Culture.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка контрольной суммы.
        /// </summary>
        internal static string CrcError {
            get {
                return ResourceManager.GetString("CrcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение в глубину для этого параметра не поддерживается, только текущее и предыдущее значение..
        /// </summary>
        internal static string DepthNotSupported {
            get {
                return ResourceManager.GetString("DepthNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при чтении даты-веремени:{0}.
        /// </summary>
        internal static string ErrorReadDT {
            get {
                return ResourceManager.GetString("ErrorReadDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие контактной крышки счетчика.
        /// </summary>
        internal static string EvAccess1 {
            get {
                return ResourceManager.GetString("EvAccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие контактной крышки счетчика.
        /// </summary>
        internal static string EvAccess2 {
            get {
                return ResourceManager.GetString("EvAccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие корпуса счетчика.
        /// </summary>
        internal static string EvAccess3 {
            get {
                return ResourceManager.GetString("EvAccess3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие корпуса счетчика.
        /// </summary>
        internal static string EvAccess4 {
            get {
                return ResourceManager.GetString("EvAccess4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено количество попыток ввода пароля.
        /// </summary>
        internal static string EvAccess5 {
            get {
                return ResourceManager.GetString("EvAccess5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало воздействия магнитным полем.
        /// </summary>
        internal static string EvArchErr1 {
            get {
                return ResourceManager.GetString("EvArchErr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка записи часов реального времени.
        /// </summary>
        internal static string EvArchErr10 {
            get {
                return ResourceManager.GetString("EvArchErr10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка температурной компенсации часов.
        /// </summary>
        internal static string EvArchErr11 {
            get {
                return ResourceManager.GetString("EvArchErr11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание воздействия магнитным полем.
        /// </summary>
        internal static string EvArchErr2 {
            get {
                return ResourceManager.GetString("EvArchErr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Низкий заряд батареи.
        /// </summary>
        internal static string EvArchErr3 {
            get {
                return ResourceManager.GetString("EvArchErr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не установлены часы реального времени.
        /// </summary>
        internal static string EvArchErr4 {
            get {
                return ResourceManager.GetString("EvArchErr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аппаратный сбой часов реального времени.
        /// </summary>
        internal static string EvArchErr5 {
            get {
                return ResourceManager.GetString("EvArchErr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка регистров накопленных значений энергии.
        /// </summary>
        internal static string EvArchErr6 {
            get {
                return ResourceManager.GetString("EvArchErr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка калибровочных значений.
        /// </summary>
        internal static string EvArchErr7 {
            get {
                return ResourceManager.GetString("EvArchErr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Батарея отсутствует.
        /// </summary>
        internal static string EvArchErr8 {
            get {
                return ResourceManager.GetString("EvArchErr8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения часов реального времени.
        /// </summary>
        internal static string EvArchErr9 {
            get {
                return ResourceManager.GetString("EvArchErr9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключение питания счетчика.
        /// </summary>
        internal static string EvDevOff {
            get {
                return ResourceManager.GetString("EvDevOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включение питания счетчика.
        /// </summary>
        internal static string EvDevOn {
            get {
                return ResourceManager.GetString("EvDevOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключение сетевого напряжения.
        /// </summary>
        internal static string EvDevPit {
            get {
                return ResourceManager.GetString("EvDevPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись суточной таблицы энергии.
        /// </summary>
        internal static string EvProgr1 {
            get {
                return ResourceManager.GetString("EvProgr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синхронизация времени.
        /// </summary>
        internal static string EvProgr10 {
            get {
                return ResourceManager.GetString("EvProgr10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись сетевого адреса.
        /// </summary>
        internal static string EvProgr11 {
            get {
                return ResourceManager.GetString("EvProgr11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись идентификатора пользователя.
        /// </summary>
        internal static string EvProgr12 {
            get {
                return ResourceManager.GetString("EvProgr12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись параметров дисплея.
        /// </summary>
        internal static string EvProgr13 {
            get {
                return ResourceManager.GetString("EvProgr13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись параметров оптопорта.
        /// </summary>
        internal static string EvProgr14 {
            get {
                return ResourceManager.GetString("EvProgr14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись параметров RS485.
        /// </summary>
        internal static string EvProgr15 {
            get {
                return ResourceManager.GetString("EvProgr15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись параметров дополнительного интерфейса.
        /// </summary>
        internal static string EvProgr16 {
            get {
                return ResourceManager.GetString("EvProgr16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись параметров телеметрии.
        /// </summary>
        internal static string EvProgr17 {
            get {
                return ResourceManager.GetString("EvProgr17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись коэффициента трансформации тока.
        /// </summary>
        internal static string EvProgr18 {
            get {
                return ResourceManager.GetString("EvProgr18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись коэффициента трансформации напряжения.
        /// </summary>
        internal static string EvProgr19 {
            get {
                return ResourceManager.GetString("EvProgr19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись суточной таблицы мощности.
        /// </summary>
        internal static string EvProgr2 {
            get {
                return ResourceManager.GetString("EvProgr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись интервала интеграции.
        /// </summary>
        internal static string EvProgr20 {
            get {
                return ResourceManager.GetString("EvProgr20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись лимитов мощности.
        /// </summary>
        internal static string EvProgr21 {
            get {
                return ResourceManager.GetString("EvProgr21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись лимита энергии.
        /// </summary>
        internal static string EvProgr22 {
            get {
                return ResourceManager.GetString("EvProgr22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установка режима функционального светодиода.
        /// </summary>
        internal static string EvProgr23 {
            get {
                return ResourceManager.GetString("EvProgr23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись основного тарифного расписания.
        /// </summary>
        internal static string EvProgr3 {
            get {
                return ResourceManager.GetString("EvProgr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись резервного тарифного расписания.
        /// </summary>
        internal static string EvProgr4 {
            get {
                return ResourceManager.GetString("EvProgr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись Флагов пасхи и радуницы.
        /// </summary>
        internal static string EvProgr5 {
            get {
                return ResourceManager.GetString("EvProgr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись даты и времени переключения с основного на резервное расписание.
        /// </summary>
        internal static string EvProgr6 {
            get {
                return ResourceManager.GetString("EvProgr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись дат и времен автоматического перевода времени на летний/зимний период.
        /// </summary>
        internal static string EvProgr7 {
            get {
                return ResourceManager.GetString("EvProgr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись даты и времени.
        /// </summary>
        internal static string EvProgr8 {
            get {
                return ResourceManager.GetString("EvProgr8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись пароля.
        /// </summary>
        internal static string EvProgr9 {
            get {
                return ResourceManager.GetString("EvProgr9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального напряжения фазы A.
        /// </summary>
        internal static string EvSostFaz1 {
            get {
                return ResourceManager.GetString("EvSostFaz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет напряжения на фазе C.
        /// </summary>
        internal static string EvSostFaz10 {
            get {
                return ResourceManager.GetString("EvSostFaz10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Падение напряжения фазы C ниже допустимого.
        /// </summary>
        internal static string EvSostFaz11 {
            get {
                return ResourceManager.GetString("EvSostFaz11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого напряжения фазы C.
        /// </summary>
        internal static string EvSostFaz12 {
            get {
                return ResourceManager.GetString("EvSostFaz12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального тока фазы A.
        /// </summary>
        internal static string EvSostFaz13 {
            get {
                return ResourceManager.GetString("EvSostFaz13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого тока фазы A.
        /// </summary>
        internal static string EvSostFaz14 {
            get {
                return ResourceManager.GetString("EvSostFaz14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального тока фазы B.
        /// </summary>
        internal static string EvSostFaz15 {
            get {
                return ResourceManager.GetString("EvSostFaz15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого тока фазы B.
        /// </summary>
        internal static string EvSostFaz16 {
            get {
                return ResourceManager.GetString("EvSostFaz16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального тока фазы C.
        /// </summary>
        internal static string EvSostFaz17 {
            get {
                return ResourceManager.GetString("EvSostFaz17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого тока фазы C.
        /// </summary>
        internal static string EvSostFaz18 {
            get {
                return ResourceManager.GetString("EvSostFaz18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет напряжения на фазе A.
        /// </summary>
        internal static string EvSostFaz2 {
            get {
                return ResourceManager.GetString("EvSostFaz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Падение напряжения фазы A ниже допустимого.
        /// </summary>
        internal static string EvSostFaz3 {
            get {
                return ResourceManager.GetString("EvSostFaz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого напряжения фазы A.
        /// </summary>
        internal static string EvSostFaz4 {
            get {
                return ResourceManager.GetString("EvSostFaz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального напряжения фазы B.
        /// </summary>
        internal static string EvSostFaz5 {
            get {
                return ResourceManager.GetString("EvSostFaz5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет напряжения на фазе B.
        /// </summary>
        internal static string EvSostFaz6 {
            get {
                return ResourceManager.GetString("EvSostFaz6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Падение напряжения фазы B ниже допустимого.
        /// </summary>
        internal static string EvSostFaz7 {
            get {
                return ResourceManager.GetString("EvSostFaz7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышение допустимого напряжения фазы B.
        /// </summary>
        internal static string EvSostFaz8 {
            get {
                return ResourceManager.GetString("EvSostFaz8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление нормального напряжения фазы C.
        /// </summary>
        internal static string EvSostFaz9 {
            get {
                return ResourceManager.GetString("EvSostFaz9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ответе не найден KI.
        /// </summary>
        internal static string NoKI {
            get {
                return ResourceManager.GetString("NoKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ответе не найден KU.
        /// </summary>
        internal static string NoKU {
            get {
                return ResourceManager.GetString("NoKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет значения в счетчике.
        /// </summary>
        internal static string NoLast {
            get {
                return ResourceManager.GetString("NoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ответе не найден серийный номер.
        /// </summary>
        internal static string NoSN {
            get {
                return ResourceManager.GetString("NoSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибор &apos;{0}&apos; не подерживает параметр {1}, дискретность {2}{3}. Рекомендуем обновить прошивку прибора.
        /// </summary>
        internal static string NOT_PARAM {
            get {
                return ResourceManager.GetString("NOT_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок ответа посылки не соответсвует заголовку запроса..
        /// </summary>
        internal static string NotEqualAnswerPacket {
            get {
                return ResourceManager.GetString("NotEqualAnswerPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение мгновенных значений. Результат: {0}.
        /// </summary>
        internal static string READ_IM {
            get {
                return ResourceManager.GetString("READ_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение KI: {0}, KU:{1}.
        /// </summary>
        internal static string ReadKPRKIKU {
            get {
                return ResourceManager.GetString("ReadKPRKIKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время дыры:{0} не совпало с временем среза:{1}.
        /// </summary>
        internal static string SliceTimeNotEqual {
            get {
                return ResourceManager.GetString("SliceTimeNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение времени.
        /// </summary>
        internal static string Test_DT {
            get {
                return ResourceManager.GetString("Test_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение серийного номера.
        /// </summary>
        internal static string Test_SN {
            get {
                return ResourceManager.GetString("Test_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтение версии.
        /// </summary>
        internal static string Test_SV {
            get {
                return ResourceManager.GetString("Test_SV", resourceCulture);
            }
        }
    }
}
