//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Services.Drv.Emera.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sys.Services.Drv.Emera.Culture.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррестировка времени кнопками.
        /// </summary>
        internal static string ADJUSTMENT_TIME_BUTTONS {
            get {
                return ResourceManager.GetString("ADJUSTMENT_TIME_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррестировка времени по каналам связи.
        /// </summary>
        internal static string ADJUSTMENT_TIME_CHANNELS {
            get {
                return ResourceManager.GetString("ADJUSTMENT_TIME_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение администратора.
        /// </summary>
        internal static string ADMIN_RESET {
            get {
                return ResourceManager.GetString("ADMIN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза А:откл.
        /// </summary>
        internal static string AOFF {
            get {
                return ResourceManager.GetString("AOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза А:вкл.
        /// </summary>
        internal static string AON {
            get {
                return ResourceManager.GetString("AON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибочный аргумент.
        /// </summary>
        internal static string ARGUMENT {
            get {
                return ResourceManager.GetString("ARGUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (авто.расчет сезона лето).
        /// </summary>
        internal static string AUTO_CALC_SUMMER_SEASON {
            get {
                return ResourceManager.GetString("AUTO_CALC_SUMMER_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (авто.расчет сезона зима).
        /// </summary>
        internal static string AUTO_CALC_WINTER_SEASON {
            get {
                return ResourceManager.GetString("AUTO_CALC_WINTER_SEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блок поврежден.
        /// </summary>
        internal static string BLOCK_DAMAGED {
            get {
                return ResourceManager.GetString("BLOCK_DAMAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза B:откл.
        /// </summary>
        internal static string BOFF {
            get {
                return ResourceManager.GetString("BOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза B:вкл.
        /// </summary>
        internal static string BON {
            get {
                return ResourceManager.GetString("BON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрыв цепей ABC напряжения U или (и) тока I. .
        /// </summary>
        internal static string CHAIN_TERM {
            get {
                return ResourceManager.GetString("CHAIN_TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        internal static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение параметров телеметрии.
        /// </summary>
        internal static string CHANGE_SET_TELEMETRY {
            get {
                return ResourceManager.GetString("CHANGE_SET_TELEMETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение констант.
        /// </summary>
        internal static string CHANGING_CONSTANTS {
            get {
                return ResourceManager.GetString("CHANGING_CONSTANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение даты переключения сезонов.
        /// </summary>
        internal static string CHANGING_DATE_CHANGE_SEASONS {
            get {
                return ResourceManager.GetString("CHANGING_DATE_CHANGE_SEASONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (зав. номер).
        /// </summary>
        internal static string CHG_ID {
            get {
                return ResourceManager.GetString("CHG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (номер пользователя).
        /// </summary>
        internal static string CHG_ID_USER {
            get {
                return ResourceManager.GetString("CHG_ID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (KI KU или формат отображения).
        /// </summary>
        internal static string CHG_KI_KU_FORMAT {
            get {
                return ResourceManager.GetString("CHG_KI_KU_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (маска отображения).
        /// </summary>
        internal static string CHG_MASK_VIEW {
            get {
                return ResourceManager.GetString("CHG_MASK_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (сетевой адрес).
        /// </summary>
        internal static string CHG_NET_ID {
            get {
                return ResourceManager.GetString("CHG_NET_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (параметры порта).
        /// </summary>
        internal static string CHG_PORT_SETT {
            get {
                return ResourceManager.GetString("CHG_PORT_SETT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (тип прибора).
        /// </summary>
        internal static string CHG_TYPE_EQUIPMENT {
            get {
                return ResourceManager.GetString("CHG_TYPE_EQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие крышки счетчика.
        /// </summary>
        internal static string CLOSING_COUNTER {
            get {
                return ResourceManager.GetString("CLOSING_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза C:откл.
        /// </summary>
        internal static string COFF {
            get {
                return ResourceManager.GetString("COFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фаза C:вкл.
        /// </summary>
        internal static string CON {
            get {
                return ResourceManager.GetString("CON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка контрольной суммы.
        /// </summary>
        internal static string CRC {
            get {
                return ResourceManager.GetString("CRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поврежен файл калибровки.
        /// </summary>
        internal static string DAMAGE_CALIBRATION_FILE {
            get {
                return ResourceManager.GetString("DAMAGE_CALIBRATION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Неисправно EEPROM 1).
        /// </summary>
        internal static string DEFECTIVE_EEPROM_1 {
            get {
                return ResourceManager.GetString("DEFECTIVE_EEPROM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Неисправно EEPROM 2).
        /// </summary>
        internal static string DEFECTIVE_EEPROM_2 {
            get {
                return ResourceManager.GetString("DEFECTIVE_EEPROM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Неисправно OЗУ).
        /// </summary>
        internal static string DEFECTIVE_OZU {
            get {
                return ResourceManager.GetString("DEFECTIVE_OZU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Неисправно ПЗУ).
        /// </summary>
        internal static string DEFECTIVE_PZU {
            get {
                return ResourceManager.GetString("DEFECTIVE_PZU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счетчик занят.
        /// </summary>
        internal static string DEVICE_BUSY {
            get {
                return ResourceManager.GetString("DEVICE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрошенный срез отличается от полученного. Возможно это связано с неточным временем.
        /// </summary>
        internal static string ERROR_CUT {
            get {
                return ResourceManager.GetString("ERROR_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ошибка DSP).
        /// </summary>
        internal static string ERROR_DSP {
            get {
                return ResourceManager.GetString("ERROR_DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ошибка обмена с DSP).
        /// </summary>
        internal static string ERROR_EXCHANGE_DSP {
            get {
                return ResourceManager.GetString("ERROR_EXCHANGE_DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал событий.
        /// </summary>
        internal static string EVENTS_DESC {
            get {
                return ResourceManager.GetString("EVENTS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная функция.
        /// </summary>
        internal static string FUNCTION {
            get {
                return ResourceManager.GetString("FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мгновенные значения.
        /// </summary>
        internal static string IM_DESC {
            get {
                return ResourceManager.GetString("IM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат пакета.
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (режим калибровки).
        /// </summary>
        internal static string M_CALIBRATE {
            get {
                return ResourceManager.GetString("M_CALIBRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (нормальный режим).
        /// </summary>
        internal static string M_NORM {
            get {
                return ResourceManager.GetString("M_NORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (режим поверки).
        /// </summary>
        internal static string M_VERIFICATION {
            get {
                return ResourceManager.GetString("M_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аппаратная ошибка.
        /// </summary>
        internal static string MACHINE_ERROR {
            get {
                return ResourceManager.GetString("MACHINE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнуление максимальной мощности.
        /// </summary>
        internal static string MAX_POWER_RESET {
            get {
                return ResourceManager.GetString("MAX_POWER_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка памяти.
        /// </summary>
        internal static string MEMORY_ERROR {
            get {
                return ResourceManager.GetString("MEMORY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение режима.
        /// </summary>
        internal static string MODE_CHANGE {
            get {
                return ResourceManager.GetString("MODE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помехи в сети.
        /// </summary>
        internal static string NETWORK_PROBLEMS {
            get {
                return ResourceManager.GetString("NETWORK_PROBLEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не соответствие запрошенного и ответившего сетевого адреса.
        /// </summary>
        internal static string NOT_COMPLIANT_ADDRESS {
            get {
                return ResourceManager.GetString("NOT_COMPLIANT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не соответствие запрошенной и ответившей функции.
        /// </summary>
        internal static string NOT_COMPLIANT_FUNCTION {
            get {
                return ResourceManager.GetString("NOT_COMPLIANT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая конфигурация не позволяет выполнение команды.
        /// </summary>
        internal static string NOT_CORRESPOND_TO_CONFIG {
            get {
                return ResourceManager.GetString("NOT_CORRESPOND_TO_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибор &apos;{0}&apos; не подерживает параметр {1}, дискретность {2}{3}. Рекомендуем обновить прошивку прибора.
        /// </summary>
        internal static string NOT_PARAM {
            get {
                return ResourceManager.GetString("NOT_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытие крышки счетчика.
        /// </summary>
        internal static string OPENING_COUNTER {
            get {
                return ResourceManager.GetString("OPENING_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для работы с оптопортом нажмите кнопку Доступ.
        /// </summary>
        internal static string OPTOPORT_ERROR {
            get {
                return ResourceManager.GetString("OPTOPORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ненормальная длина пакета.
        /// </summary>
        internal static string PACKET_LENGTH_ABNORMAL {
            get {
                return ResourceManager.GetString("PACKET_LENGTH_ABNORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный параметр.
        /// </summary>
        internal static string PARAMETER {
            get {
                return ResourceManager.GetString("PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнуление энергии.
        /// </summary>
        internal static string POWER_RESET {
            get {
                return ResourceManager.GetString("POWER_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (накопленный).
        /// </summary>
        internal static string PR_ACCUM {
            get {
                return ResourceManager.GetString("PR_ACCUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (суточный).
        /// </summary>
        internal static string PR_DAY {
            get {
                return ResourceManager.GetString("PR_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (месячный).
        /// </summary>
        internal static string PR_MONTH {
            get {
                return ResourceManager.GetString("PR_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (годовой).
        /// </summary>
        internal static string PR_YEAR {
            get {
                return ResourceManager.GetString("PR_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение мгновенных значений. Результат: {0}.
        /// </summary>
        internal static string READ_IM {
            get {
                return ResourceManager.GetString("READ_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение 30-и минутных.
        /// </summary>
        internal static string Read30Min {
            get {
                return ResourceManager.GetString("Read30Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение 3-х минутных.
        /// </summary>
        internal static string Read3Min {
            get {
                return ResourceManager.GetString("Read3Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение суточных.
        /// </summary>
        internal static string ReadDay {
            get {
                return ResourceManager.GetString("ReadDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение дыр: От времени {0} Глубиной:{1} До макс.времени:{2} =&gt;выч.нач.время:{3} дыр:{4}.
        /// </summary>
        internal static string ReadHoles {
            get {
                return ResourceManager.GetString("ReadHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение KU:{0}.
        /// </summary>
        internal static string ReadKU {
            get {
                return ResourceManager.GetString("ReadKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение месячных.
        /// </summary>
        internal static string ReadMonth {
            get {
                return ResourceManager.GetString("ReadMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение годовых.
        /// </summary>
        internal static string ReadYear {
            get {
                return ResourceManager.GetString("ReadYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение расписания выходных дней.
        /// </summary>
        internal static string RESCHEDULE_HOLIDAYS {
            get {
                return ResourceManager.GetString("RESCHEDULE_HOLIDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканирование пароля.
        /// </summary>
        internal static string SCAN_PASSWORD {
            get {
                return ResourceManager.GetString("SCAN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (сезона лето).
        /// </summary>
        internal static string SEASON_SUMMER {
            get {
                return ResourceManager.GetString("SEASON_SUMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (сезона зима).
        /// </summary>
        internal static string SEASON_WINTER {
            get {
                return ResourceManager.GetString("SEASON_WINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнуление срезов.
        /// </summary>
        internal static string SEGMENTS_RESET {
            get {
                return ResourceManager.GetString("SEGMENTS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синхронизация архива.
        /// </summary>
        internal static string SYNC_ARCH {
            get {
                return ResourceManager.GetString("SYNC_ARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение тарифного расписания.
        /// </summary>
        internal static string TARIFF_SCHEDULE_CHANGE {
            get {
                return ResourceManager.GetString("TARIFF_SCHEDULE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключение защиты.
        /// </summary>
        internal static string Test_DisableProtection {
            get {
                return ResourceManager.GetString("Test_DisableProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение времени.
        /// </summary>
        internal static string Test_DT {
            get {
                return ResourceManager.GetString("Test_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка границ архива.
        /// </summary>
        internal static string Test_Error_Req {
            get {
                return ResourceManager.GetString("Test_Error_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение коэф..
        /// </summary>
        internal static string Test_KIKU {
            get {
                return ResourceManager.GetString("Test_KIKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение коэф. преобразования.
        /// </summary>
        internal static string Test_KPr {
            get {
                return ResourceManager.GetString("Test_KPr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение серийного номера.
        /// </summary>
        internal static string Test_SN {
            get {
                return ResourceManager.GetString("Test_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение версии.
        /// </summary>
        internal static string Test_SV {
            get {
                return ResourceManager.GetString("Test_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбой часов реального времени.
        /// </summary>
        internal static string TIME_CLOCK_FAILTURE {
            get {
                return ResourceManager.GetString("TIME_CLOCK_FAILTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустиммая тарифная программа.
        /// </summary>
        internal static string UNACCEPTABLE_TARIFF {
            get {
                return ResourceManager.GetString("UNACCEPTABLE_TARIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несанкционированный доступ.
        /// </summary>
        internal static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (для выходных).
        /// </summary>
        internal static string WEEKEND_DAYS {
            get {
                return ResourceManager.GetString("WEEKEND_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (для рабочих дней).
        /// </summary>
        internal static string WORKING_DAYS {
            get {
                return ResourceManager.GetString("WORKING_DAYS", resourceCulture);
            }
        }
    }
}
